DROP TABLE IF EXISTS ghosts;

CREATE TABLE ghosts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    img VARCHAR NOT NULL,
    tagline VARCHAR NOT NULL,
    backstory VARCHAR NOT NULL
);